#+TITLE: TRABAJO MONOGRÁFICO - ESTUDIO DEL TRABAJO
#+AUTHOR: Augusto Riedinger
#+STARTUP: folded

* CONTENIDOS :toc:
- [[#estudio-del-trabajo][ESTUDIO DEL TRABAJO]]
  - [[#frederic-taylor-1856-1915][FREDERIC TAYLOR 1856-1915]]
  - [[#frank-y-lillian-gilbreth-1900s][FRANK Y LILLIAN GILBRETH (1900s)]]
- [[#estudio-de-tiempos-y-movimientos][ESTUDIO DE TIEMPOS Y MOVIMIENTOS]]
  - [[#concepto][CONCEPTO]]
  - [[#cronocinergología][CRONOCINERGOLOGÍA]]
  - [[#simbología][SIMBOLOGÍA]]
  - [[#mediciones][MEDICIONES]]
  - [[#fatiga---stress-laboral][FATIGA - STRESS LABORAL]]
  - [[#egonomía][EGONOMÍA]]
  - [[#seguridad][SEGURIDAD]]
  - [[#conclusion][CONCLUSION]]

* ESTUDIO DEL TRABAJO
La Organización Internacional del Trabajo (OIT) describe al estudio del trabajo como "/[...]el examen sistemático de los métodos para realizar las actividades con el fin de mejorar la utilización eficaz de los recursos y de establecer normas de rendimiento con respecto a las actividades que se están realizando/".

Ésta disciplina es aplicable en diferentes campos, industrias, empresas instituciones sociales, etc.; y fue desarrollada ampliamente a lo largo de la historia. A continuación se estudiarán los diferentes puntos de vista de autores en función del contexto histórico al que pertenecían.

** FREDERIC TAYLOR 1856-1915
Considerado el padre de la dirección científica y de la ingeniería industrial, Taylor fie el primero en desarrollar una teoría integrada de los principios y metodologías de la administración. Sus principales contribuciones:
 + Determinación científica de los estándares de trabajo - tiempos de trabajo y estandarización de herramientas.
 + Desarrollo de sistema basado en tareas.
 + División del trabajo en elementos para determinar los tiempos de tareas.

** FRANK Y LILLIAN GILBRETH (1900s)
Desarrollo del estudio de los movimientos como una técnica de la ingeniería y la dirección. Frank Gilbreth continuó su estudio y análisis de movimientos en otros campos, y ambos fueron pioneros de los filmes del movimiento para el estudio de obreros y tareas. Frank desarrolló el estudio de micro-movimientos: descomposición del trabajo en elementos fundamentales llamados "Thebligs". Sus aportes han sido grandes en las áreas de estudio de concesiones por fatiga, organización del hogar y asuntos similares.
 + Estudio de los movimientos de los trabajadores para eliminar innecesarios y lograr eficiencia máxima.
 + Diseño de tecnología cinematográfica par el estudio de movimientos.

* ESTUDIO DE TIEMPOS Y MOVIMIENTOS
** CONCEPTO
El estudio de tiempos y movimientos es una herramienta para la medición del trabajo utilizada con éxito desde finales del siglo XIX que combina el estudio de tiempos realizado por Taylor junto con el trabajo de estudio de movimientos de Frank y Lillian Gilbreth. A través de los años dichos estudios han ayudado a solucionar multitud de problemas de producción y a reducir costos.
 + *Estudio de tiempos*: actividad que implica la técnica de establecer un estándar de tiempo permisible para realizar una tarea determinada, con base en la medición del contenido de trabajo del método preciso, con la debida consideración de la fatiga y las demoras personales; así como también los retrasos innevitables.
 + *Estudio de movimientos*: análisis cuidadoso de diversos movimietos que efectúa el cuerpo al ejecutar un trabajo.
** CRONOCINERGOLOGÍA
Los Gilbreth desarrollaron en 1913 el cronociclografo, un dispositivo para medir y capturar movimientos. Consistía en poner luces sobre las extremidades que se fueran a mover y tomar una fotografía de largo exposición. Ellos dividieron el trabajo en sus elementos más básicos, a los que llamaban Therbligs, y a los cuales estudiaban por sí mismos con fotos de este tipo. Las luces que se les había puesto a los empleados se prendían 20 veces por segundo y el obturador de la cámara se abría al inicio del ciclo de trabajo y no se cerraba hasta que este hubiera finalizado. Esto daba como resultado una imagen en la que se podía seguir el trayecto del trabajador a través de la línea de intermitencia lumínica que dejaban las luces. En consecuencia, con el cronociclografo, es posible calcular velocidad, aceleración y desaceleración, así como estudiar los movimientos del cuerpo.
** SIMBOLOGÍA
Con la división del trabajo en 17 movimientos fundamentales Therbligs, donde cada uno identifica un símbolo, gráfico, color y letra o sigla:
|--------------------+---------+-----------+----------------|
| *SIGNIFICADO*      | *SIGLA* | *SÍMBOLO* | *COLOR*        |
|--------------------+---------+-----------+----------------|
| Buscar             | B       | $\theta$  | Negro          |
| Seleccionar        | SE      | ->        | Gris claro     |
| Tomar              | T       |           | Verde claro    |
| Mover              | M       |           | Verde          |
| Sostener           | SO      |           | Dorado         |
| Soltar             | SL      |           | Carmin         |
| Colocar            | P       |           | Azul           |
| Precolocar         | PP      |           | Azul claro     |
| Inspeccionar       | I       |           | Ocre           |
| Ensamblar          | E       |           | Violeta oscuro |
| Usar               | U       |           |                |
| Retraso inivitable | DI      |           |                |
| Retraso evitable   | DEV     |           |                |
| Planear            | PL      |           |                |
| Descansar          | DES     |           |                |
** MEDICIONES
En la actividad de la empresa, el factor tiempo juega un papel preponderante. La determinación de tiempos de uan actividad a partir de un estudio de tiempos por cronometraje está situada dentro de las técnicas de capacitación de datos reales a partir de la medición de la tarea por medio de cronometrado de la misma. Ésta técnica nos permite disponer del tiempo de una operación con adecuado nivel de confianza y reducido márgen de error. Una vez cumplida la etapa de registrar los tiempos, estamos en condiciones de iniciar la etapa denominada *medios*, en la que podemos identificar las actividades de preparación y medición propiamente dicha. Ellas son:
 1. Sistema de cronometrado.
 1. Los tipos de cronómetros habituales.
 1. La extensión del estudio
 1. El concepto de valoración

Se debe cronometrar el tiempo de proceso completo, desde que empieza hasta que termina. Este estudio lo llevaremos a cabo mediante hojas de tiempos, en donde ayuda a la compilación y el análisis de lso datos que se recojan. Una vez cronometrados todos los tiempos y recogidos en las hojas de tiempo, se pasa a calcular el tiempo estándar para cada uno de los procesos. Una vez calculado, se obtendrá un ritmo de trabajo, que podrá ser utilizado para establecer un tiempo mínimo exigible al trabajador.
** FATIGA - STRESS LABORAL
Si bien las consecuencias del ritmo diario pueden ser de algún modo amortiguadas por la persona, la situación corporal del individuo tiene relación a su edad, dado que en la medida que aumenta la edad disminuye las capacidades corporales como la fuerza muscular, la capacidad intelectual, el rendimiento de los órganos, etc.

Una de las consecuencias que pueden surgir por el ritmo diario de la empresa es la fatíga, que es un fenómeno periódico en todo organismo vivo que se traduce en una pérdida de capacidad de rendimiento, y es compensada mediante el descanso suficiente. Puede considerarse por tres aspectos suficientes:

 1. Biológica, debido al funcionamiento propio del organismo de la persona.
 1. Laboral, debida al desgaste de las fuerzas físicas producidas por las condiciones del trabajo.
 1. De los impulsos, la cual se hace presente en el trabajador en creciente desgaste de fuerza y falta de interés por la tarea, dolores corporales y sensaciones de agotamiento que producen una disminución de rendimientos.
** EGONOMÍA
Para tratar de evitar una fatíga en los trabajadores se inició el estudio de la ergonomía: disciplina que se encarga del diseño de lugares de trabajo, herramientas y tareas, de modo que coincidan con las características psicológicas, anatómicas y las capacidades de los trabajadores que se verán involucrados. Se basa en la optimización de tres elementos del sistema (humano-máquina-ambiente), para lo cuál se elaboran métodos de la persona, de la técnica y de la optimización.
** SEGURIDAD
Es indispensable la importancia que tiene la relación entre el estudio del trabajo y la seguridad e higiene industrial, basada en la higiene del lugar de trabajo y la seguridad del trabajador.

La seguridad industrial es la aplicación de técnicas para la reducción, control y eleminación de los accidentes y enfermedades de trabajo.

Lo más importante para la prevención de los accidentes de trabajo radica en las acciones correctas que se emplean, con base en el análisis de las causas que condujeron a la producción de los percances. En orden de importancia, podemos mencionar los siguientes medios:

 + Selección adecuada del personal.
 + Educación sistemática.
 + Recolocación del trabajador.
 + Revisión técnica periódica.
 + Tratamiento médico.
 + Orientación psíquica.
 +
** CONCLUSION
Para concluir, se puede asegurar que el estudio del trabajo es el análisis del trabajo para su mejor realización, ya sea en tiempos, productividad, calidad, etc. Mediante el uso de minuciosas observaciones de las actividades que se realizan dentro de una fábrica, taller o lugar que se utiliza para la producción de algún objeto, para poder encontrar posibles fallas o errores durante el proceso de fabricación, y posteriormente corregir esos errores y establecer un mejor método, económico y/o práctico
